resource "local_file" "env_file" {
  content = <<EOT

MEDIATOR_DB_PORT=${var.mediator_db_port}
KEYCLOAK_DB_PORT=${var.keycloak_db_port}
RDS_DATABASE_HOST=${jsonencode(var.RDS_database_host)}
RDS_DATABASE_PORT=${jsonencode(var.RDS_database_port)}
RDS_DATABASE_NAME=${jsonencode(var.RDS_database_name)}
RDS_DATABASE_USER=${jsonencode(var.RDS_database_user)}
DB_INSTANCE_PRIVATE_IPS=${jsonencode(var.db_instance_private_ipse)}
NATS_INSTANCE_PRIVATE_IPS=${jsonencode(var.nats_instance_private_ips)}
EC2_DB_USER=${join(",", var.db_users)}
EC2_DB_PASSWORD=${join(",", var.db_passwords)}
EC2_DB_DATABASE=${join(",", var.db_names)}


EOT
  filename = "application.env"
}


resource "local_file" "env" {
  content = <<EOT
  OOB_BATCH_SIZE=10
BRAND_LOGO=

PLATFORM_PROFILE_MODE=${var.environmnet}

API_GATEWAY_PROTOCOL=http
API_GATEWAY_HOST=0.0.0.0
API_GATEWAY_PORT=5000

PLATFORM_NAME=${var.project_name}
PROTOCOL=http
TENANT_EMAIL_LOGO=
API_ENDPOINT=
SOCKET_HOST=


NATS_URL=
REDIS_HOST=
REDIS_PORT=


SENDGRID_API_KEY=

FRONT_END_URL=

AGENT_PROTOCOL=https
CLUSTER_NAME=
TESKDEFINITION_FAMILY=
FILESYSTEMID=
ACCESSPOINTID=
VPC_ID=
ECS_SUBNET_ID=
AGENT_INBOUND_URL=
INBOUND_TG_ARN=
ADMIN_TG_ARN=
ALB_SECURITY_GROUP_ID=
AGENT_WEBSOCKET_PROTOCOL=http
STAGE=${var.environmnet}
AGENT_URL=
EFS_SECURITY_GROUP_ID=
S3_BUCKET_ARN=
DB_SECURITY_GROUP_ID=

WALLET_STORAGE_HOST=
WALLET_STORAGE_PORT=
WALLET_STORAGE_USER=
WALLET_STORAGE_PASSWORD=

AWS_ACCOUNT_ID=
PLATFORM_WALLET_NAME=
PLATFORM_WALLET_PASSWORD=
PLATFORM_SEED=

CRYPTO_PRIVATE_KEY=
PLATFORM_URL=
PLATFORM_PROFILE_MODE=${var.environmnet}

AFJ_AGENT_SPIN_UP=/agent-provisioning/AFJ/scripts/fargate.sh
AFJ_AGENT_ENDPOINT_PATH=/agent-provisioning/AFJ/endpoints/
AFJ_AGENT_TOKEN_PATH=/agent-provisioning/AFJ/token/
PLATFORM_ID=1
AFJ_VERSION=
PLATFORM_ADMIN_EMAIL=


AFJ_IMAGE_URL=
FIDO_API_ENDPOINT=

DATABASE_URL=
POOL_DATABASE_URL=

PLATFORM_NAME=
PLATFORM_LOGO=
POWERED_BY=
PLATFORM_WEB_URL=
POWERED_BY_URL=

UPLOAD_LOGO_HOST=
API_GATEWAY_PROTOCOL_SECURE=http

USER_NKEY_SEED=

API_GATEWAY_NKEY_SEED=

ORGANIZATION_NKEY_SEED=

AGENT_PROVISIONING_NKEY_SEED=

AGENT_SERVICE_NKEY_SEED=

VERIFICATION_NKEY_SEED=

LEDGER_NKEY_SEED=

ISSUANCE_NKEY_SEED=

CONNECTION_NKEY_SEED=

ECOSYSTEM_NKEY_SEED=

CREDENTAILDEFINITION_NKEY_SEED=

SCHEMA_NKEY_SEED=

UTILITIES_NKEY_SEED=


KEYCLOAK_DOMAIN=
KEYCLOAK_ADMIN_URL=
KEYCLOAK_MASTER_REALM=
KEYCLOAK_MANAGEMENT_CLIENT_ID=
KEYCLOAK_MANAGEMENT_CLIENT_SECRET=
KEYCLOAK_REALM=


#access S3 for organization
AWS_ORG_LOGO_BUCKET_NAME=
AWS_PUBLIC_REGION=

EOT
  filename = "${var.environmnet}.env"
}
